---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cobaia-argocd
  name: cobaia-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cobaia-argocd
  template:
    metadata:
      labels:
        app: cobaia-argocd
    spec:
      containers:
      - image: httpd
        name: httpd-24
