---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: lab-app
  name: lab-app
spec:
  serviceAccountName: argo-app
  containers:
  - image: nginx
    name: lab-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:scc:anyuid
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:anyuid
subjects:
- kind: ServiceAccount
  name: argo-app
  namespace: argo-app
