apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -qa
commonLabels:
  app: billing-qa
resources:
  - ../../base
patches:
  - patch: |-
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        annotations:
          openshift.io/host.generated: "true"
        labels:
          app: billing
        name: billing
      spec:
        host: billing-qa.apps.diolivei.vmware.tamlab.rdu2.redhat.com
