---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-billing 
  namespace: openshift-gitops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/doliveiraorg/cobaia-argocd.git
      revision: HEAD
      directories:
      - path: apps/billing/envs/*
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/doliveiraorg/cobaia-argocd.git
        targetRevision: HEAD
        path: 'apps/billing/envs/{{ .path.basename }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'deployment'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
